package com.stark.learning.testing

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.AdapterView
import android.widget.ArrayAdapter
import androidx.recyclerview.widget.StaggeredGridLayoutManager
import com.stark.learning.R
import com.stark.learning.recyclerview.StaggeredRecyclerView
import com.stark.learning.util.showIAlertDialog
import kotlinx.android.synthetic.main.activity_test.*
import kotlinx.android.synthetic.main.fragment_bottom_sheet.*
import kotlinx.android.synthetic.main.fragment_bottom_sheet.dummyList

class TestActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.fragment_bottom_sheet)


        dummyList.layoutManager = StaggeredGridLayoutManager(2,
            StaggeredGridLayoutManager.VERTICAL).apply {
            gapStrategy = StaggeredGridLayoutManager.GAP_HANDLING_MOVE_ITEMS_BETWEEN_SPANS
        }
        dummyList.adapter = StaggeredRecyclerView(
            mutableListOf(
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert","Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment","Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment","Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment","Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment","Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment","Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment",
                "Test Activity",
                "Rotate Image",
                "Rotate Images",
                "IAlert",
                "Recycler View",
                "C layout",
                "Bottom Layout",
                "Bottom Sheet Fragment"
            )) {}


        /* dummyList.adapter = ArrayAdapter<String>(con,
            android.R.layout.simple_list_item_1,
            mutableListOf(
                "1","2","3","4","5",
                "6","1","2","3","4","5",
                "6","1","2","3","4","5","6",
                "1","2","3","4","5","6","1","2",
                "3","4","5","6",
                "1","2","3","4","5","6",
                "1","2","3","4","5","6","1",
                "2","3","4","5","6","1","2","3",
                "4","5","6","1","2","3","4","5","6"
            )
        )*/


        /*   dummyList.onItemClickListener =
            AdapterView.OnItemClickListener { _, _, position, _
                -> showIAlertDialog(this,position) }
    }*/
    }
}